###
###              ejabberd configuration file
###
### The parameters used in this configuration file are explained at
###
###       https://docs.ejabberd.im/admin/configuration
###
### The configuration file is written in YAML.
### *******************************************************
### *******           !!! WARNING !!!               *******
### *******     YAML IS INDENTATION SENSITIVE       *******
### ******* MAKE SURE YOU INDENT SECTIONS CORRECTLY *******
### *******************************************************
### Refer to http://en.wikipedia.org/wiki/YAML for the brief description.
###
websocket_ping_interval: 60
websocket_timeout: 86400

hosts:
  - localhost
  - baat.chat

loglevel: info

define_macro:
  C2S_PORT_NUMBER: 5222
  HTTP_PORT_NUMBER: 5443
  ADMIN_PORT_NUMBER: 5280


# define_macro:
#   'TLS_CIPHERS': "HIGH:!aNULL:!eNULL:!3DES:@STRENGTH"
#   'TLS_OPTIONS':
#     - "no_sslv3"
#     - "no_tlsv1"
#     - "cipher_server_preference"
#     - "no_compression"
#   'DH_FILE': "/etc/ejabberd/dhparams.pem" # generated with: openssl dhparam -out dhparams.pem 2048
  

## If you already have certificates, list them here
# certfiles:
  # - /etc/ssl/ejabberd/ejabberd.pem
#  - /etc/letsencrypt/live/domain.tld/fullchain.pem
#  - /etc/letsencrypt/live/domain.tld/privkey.pem

#  c2s_dhfile: 'DH_FILE'
#  s2s_dhfile: 'DH_FILE'
#  c2s_ciphers: 'TLS_CIPHERS'
#  s2s_ciphers: 'TLS_CIPHERS'
#  c2s_protocol_options: 'TLS_OPTIONS'
#  s2s_protocol_options: 'TLS_OPTIONS'


shaper:
  normal:
    rate: 3000
    burst_size: 20000
  fast: 100000

shaper_rules:
  max_user_sessions:
  - 10: admin
  - 5
  max_user_offline_messages:
    5000: admin
    1000: all
  connections_limit:
    - 5
  download_speed:
    - fast: admin
    - slow: anonymous_users
    - normal
  log_days: 30
  c2s_shaper:
    none: admin
    normal: all
  s2s_shaper: fast

listen:
  -
    port: C2S_PORT_NUMBER
    ip: "::"
    module: ejabberd_c2s
    # starttls_required: false
    # protocol_options: 'TLS_OPTIONS'
    backlog: 100 #
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
  -
    port: HTTP_PORT_NUMBER
    ip: "::"
    module: ejabberd_http
    # starttls_required: false
    # protocol_options: 'TLS_OPTIONS'
    request_handlers:
      /api: mod_http_api
      /bosh: mod_bosh
      /captcha: ejabberd_captcha
      /upload: mod_http_upload
      /ws: ejabberd_http_ws
  -
    port: ADMIN_PORT_NUMBER
    ip: "::"
    module: ejabberd_http
    # starttls_required: false
    # protocol_options: 'TLS_OPTIONS'
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  # -
  #   port: 3478
  #   # ip: "::"
  #   transport: udp
  #   module: ejabberd_stun
  #   use_turn: false
  #   ## The server's public IPv4 address:
  #   # turn_ipv4_address: "203.0.113.3"
  #   ## The server's public IPv6 address:
  #   # turn_ipv6_address: "2001:db8::3"
  #-
  #  port: 1883
  #  ip: "::"
  #  module: mod_mqtt
  #  backlog: 1000

s2s_use_starttls: optional

### List of Ejabberd Modules config
modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_fail2ban: {}
  mod_http_api: {}
  mod_http_upload:
    put_url: https://@HOST@:5443/upload
    custom_headers:
      "Access-Control-Allow-Origin": "https://@HOST@"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
  mod_last: {}
  mod_mam:
    ## Mnesia is limited to 2GB, better to use an SQL backend
    ## For small servers SQLite is a good fit and is very easy
    ## to configure. Uncomment this when you have SQL configured:
    ## db_type: sql
    assume_mam_usage: true
    default: always
  mod_mqtt: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      mam: true
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ## Only accept registration requests from the "trusted"
    ## network (see access_rules section above).
    ## Think twice before enabling registration from any
    ## address. See the Jabber SPAM Manifesto for details:
    ## https://github.com/ge0rg/jabber-spam-fighting-manifesto
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_stun_disco: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false



acl:
  admin:
    user: "admin@baat.chat"
  local:
    user_regexp: ""
  loopback:
    ip:
      - 127.0.0.0/8
      - ::1/128

access_rules:
  local:
    allow: local
  c2s:
    deny: blocked
    allow: all
  announce:
    allow: admin
  configure:
    allow: admin
  muc_create:
    allow: local
  pubsub_createnode:
    allow: local
  trusted_network:
    allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      access:
        allow:
          - acl: loopback
          - acl: admin
      oauth:
        scope: "ejabberd:admin"
        access:
          allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      ip: 127.0.0.1/8
    what:
      - status
      - connected_users_number

## PG config

default_db: sql
new_sql_schema: true

sql_type: pgsql
sql_server: localhost
sql_database: ejabberd
sql_username: ejabberd
sql_password: "123456"
auth_method: sql
auth_password_format: scram



### Local Variables:
### mode: yaml
### End:
### vim: set filetype=yaml tabstop=8
